---
- hosts: all
  gather_facts: no
  become_user: idqansible
  tasks:
     - name: executing the pre bash scripts on source machines
       command: sh ./PG_Oracle_LVM_clone-pre.sh
       args: 
          chdir: /home/idqansible
       delegate_to: "{{ item }}"
       delegate_facts: true
       register: result_presource
       loop: "{{ groups['webservers'] }}"